# Generated by Django 3.2.8 on 2021-10-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_note_notename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['article']},
        ),
        migrations.AddField(
            model_name='note',
            name='article',
            field=models.CharField(help_text='Article', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='noteBody',
            field=models.TextField(help_text='Text', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='NoteContent',
        ),
    ]
