# Generated by Django 5.1.3 on 2025-06-22 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_note_groupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='groupID',
            field=models.ForeignKey(help_text='Group name', on_delete=django.db.models.deletion.PROTECT, to='catalog.group', verbose_name='Group'),
        ),
    ]
